[build]
builder = "nixpacks"
watchPatterns = ["backend/**"]

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20"]

[deploy]
startCommand = "cd backend && npm install && npm run build && npm run start"

